# Default values for borg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# Common configuration for all used images.

# The images' container registry, e.g., "docker.io"
imageRegistry: ""
# The repository base path for all component images, e.g., "lath/borg"
#
# All images are expected to be available by their service number as direct
# child under the root repository.
imageRootRepository: ""
# This sets the pull policy for all images.
imagePullPolicy: IfNotPresent
# Overrides the image tag for all images whose default is the chart appVersion.
imageTag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

gui:
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

server:
  resources: {}

tools:
  droid:
    enabled: true
    resources: {}
    configurations:
      - toolName: "DROID"
        toolVersion: "6.8.0"
        path: "/identify-file-format"
        features:
          - key: "puid"
            confidence:
              defaultValue: 0.9
          - key: "mimeType"
            confidence:
              defaultValue: 0.9
          - key: "formatName"
            confidence:
              defaultValue: 0.9
          - key: "formatVersion"
            confidence:
              defaultValue: 0.9
  tika:
    enabled: true
    resources: {}
    configurations:
      - toolName: "Tika"
        toolVersion: "2.9.2"
        path: "/extract-metadata"
        features:
          - key: "mimeType"
            confidence:
              defaultValue: 0.9
          - key: "encoding"
            confidence:
              defaultValue: 0.9
          - key: "formatVersion"
            confidence:
              defaultValue: 0.9
  magika:
    enabled: true
    resources: {}
    configurations:
      - toolName: "Magika"
        toolVersion: "0.6.0"
        path: "/identify-file-format"
        features:
          - key: "mimeType"
            confidence:
              providedByTool: true
          - key: "isText"
            confidence:
              providedByTool: true
  jhove:
    enabled: true
    resources: {}
    configurations:
      - toolName: "JHOVE (PDF-Modul)"
        toolVersion: "1.30.1"
        path: "/validate/pdf"
        trigger:
          - feature: "puid"
            regEx: "^fmt/14$" # PDF 1.0
          - feature: "puid"
            regEx: "^fmt/15$" # PDF 1.1
          - feature: "puid"
            regEx: "^fmt/16$" # PDF 1.2
          - feature: "puid"
            regEx: "^fmt/17$" # PDF 1.3
          - feature: "puid"
            regEx: "^fmt/18$" # PDF 1.4
          - feature: "puid"
            regEx: "^fmt/19$" # PDF 1.5
          - feature: "puid"
            regEx: "^fmt/20$" # PDF 1.6
          - feature: "puid"
            regEx: "^fmt/276$" # PDF 1.7
        features:
          - key: "wellFormed"
            confidence:
              defaultValue: 1.0
              conditions:
                - globalFeature: formatVersion
                  regEx: "PDF/A"
                  value: 0.0 # no PDF/A validator
          - key: "valid"
            confidence:
              defaultValue: 1.0
              conditions:
                - globalFeature: formatVersion
                  regEx: "PDF/A"
                  value: 0.0 # no PDF/A validator
          - key: "formatName"
            confidence:
              defaultValue: 0.8
              conditions:
                - globalFeature: formatVersion
                  regEx: "PDF/A"
                  value: 0.0 # no PDF/A validator
          - key: "formatVersion"
            confidence:
              defaultValue: 0.8
              conditions:
                - globalFeature: formatVersion
                  regEx: "PDF/A"
                  value: 0.0 # no PDF/A validator
      - toolName: "JHOVE (HTML-Modul)"
        toolVersion: "1.30.1"
        path: "/validate/html"
        trigger:
          - feature: "mimeType"
            regEx: "html"
          - feature: "puid"
            regEx: "^fmt/98$" # HTML 3.2
          - feature: "puid"
            regEx: "^fmt/99$" # HTML 4.0
          - feature: "puid"
            regEx: "^fmt/100$" # HTML 4.01
          # 06.11.2023: JHOVE HTML-Hul doesn't support HTML 5
        features:
          - key: "wellFormed"
            confidence:
              defaultValue: 1.0
          - key: "valid"
            confidence:
              defaultValue: 1.0
          - key: "formatName"
            confidence:
              defaultValue: 0.8
          - key: "formatVersion"
            confidence:
              defaultValue: 0.8
      - toolName: "JHOVE (TIFF-Modul)"
        toolVersion: "1.30.1"
        path: "/validate/tiff"
        trigger:
          - feature: "mimeType"
            regEx: "tiff"
          - feature: "puid"
            regEx: "^fmt/153$" # TIFF
        features:
          - key: "wellFormed"
            confidence:
              defaultValue: 1.0
          - key: "valid"
            confidence:
              defaultValue: 1.0
          - key: "formatName"
            confidence:
              defaultValue: 0.8
          - key: "formatVersion"
            confidence:
              defaultValue: 0.8
      - toolName: "JHOVE (JPEG-Modul)"
        toolVersion: "1.30.1"
        path: "/validate/jpeg"
        trigger:
          - feature: "mimeType"
            regEx: "jpeg$"
          - feature: "puid"
            regEx: "^fmt/42$" # JPEG File Interchange Format 1.00
          - feature: "puid"
            regEx: "^fmt/43$" # JPEG File Interchange Format 1.01
          - feature: "puid"
            regEx: "^fmt/44$" # JPEG File Interchange Format 1.02
        features:
          - key: "wellFormed"
            confidence:
              defaultValue: 1.0
          - key: "valid"
            confidence:
              defaultValue: 1.0
          - key: "formatName"
            confidence:
              defaultValue: 0.8
          - key: "formatVersion"
            confidence:
              defaultValue: 0.8
      - toolName: "JHOVE (JPEG2000-Modul)"
        toolVersion: "1.30.1"
        path: "/validate/jpeg2000"
        trigger:
          - feature: "mimeType"
            regEx: "jp2$"
          - feature: "puid"
            regEx: "^x-fmt/392$" # JP2 (JPEG 2000 part 1)
        features:
          - key: "wellFormed"
            confidence:
              defaultValue: 1.0
          - key: "valid"
            confidence:
              defaultValue: 1.0
          - key: "formatName"
            confidence:
              defaultValue: 0.8
          - key: "formatVersion"
            confidence:
              defaultValue: 0.8
  verapdf:
    enabled: true
    resources: {}
    configurations:
      - toolName: "veraPDF (PDF/A-1a-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/1a"
        trigger:
          - feature: "formatVersion"
            regEx: "PDF/A-1a"
          - feature: "puid"
            regEx: "^fmt/95$" # PDF/A-1a
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
      - toolName: "veraPDF (PDF/A-1b-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/1b"
        trigger:
          - feature: "formatVersion"
            regEx: "PDF/A-1b"
          - feature: "puid"
            regEx: "^fmt/354$" # PDF/A-1b
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
      - toolName: "veraPDF (PDF/A-2a-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/2a"
        trigger:
          - feature: "formatVersion"
            regEx: "PDF/A-2a"
          - feature: "puid"
            regEx: "^fmt/476$" # PDF/A-2a
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
      - toolName: "veraPDF (PDF/A-2b-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/2b"
        trigger:
          - feature: "formatVersion"
            regEx: "PDF/A-2b"
          - feature: "puid"
            regEx: "^fmt/477$" # PDF/A-2b
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
      - toolName: "veraPDF (PDF/A-2u-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/2u"
        trigger:
          - feature: "formatVersion"
            regEx: "PDF/A-2u"
          - feature: "puid"
            regEx: "^fmt/478$" # PDF/A-2u
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
      - toolName: "veraPDF (PDF/UA-Profil)"
        toolVersion: "1.26.2"
        path: "/validate/ua1"
        trigger:
          - # PDF/UA has no entry in the PRONOM database
            feature: "mimeType"
            regEx: "pdf"
        features:
          - key: "valid"
            confidence:
              defaultValue: 0.3 # temporary run for every PDF file, mostly incorrect
  odf-validator:
    enabled: true
    resources: {}
    configurations:
      - toolName: "ODF Validator"
        toolVersion: "0.12.0"
        path: "/validate"
        trigger:
          - feature: "mimeType"
            regEx: "^application/vnd\\.oasis\\.opendocument\\."
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0
  ooxml-validator:
    enabled: true
    resources: {}
    configurations:
      - toolName: "OOXML-Validator"
        toolVersion: "2.1.5"
        path: "/validate"
        trigger:
          - feature: "mimeType"
            regEx: "^application/vnd\\.openxmlformats-officedocument\\."
        features:
          - key: "valid"
            confidence:
              defaultValue: 1.0

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

shareVolume:
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  selector: {}

nodeSelector: {}

tolerations: []

affinity: {}
