apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-man.fullname" . }}-gui
  labels:
    {{- include "x-man.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "x-man.name" . }}-gui
    app.kubernetes.io/component: gui
spec:
  selector:
    matchLabels:
      {{- include "x-man.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "x-man.name" . }}-gui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "x-man.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "x-man.name" . }}-gui
        app.kubernetes.io/component: gui
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "x-man.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gui
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image:  "{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/gui:{{ .Values.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.gui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVER_API_URL
              value: http://{{ include "x-man.fullname" . }}-server/api/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
