apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-man.fullname" . }}-ldap
  labels:
    {{- include "x-man.labels" . | nindent 4 }}
    app.kubernetes.io/name: docker-test-openldap
    app.kubernetes.io/version: {{ .Values.ldap.version | quote }}
    app.kubernetes.io/component: authentication
spec:
  selector:
    matchLabels:
      {{- include "x-man.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: docker-test-openldap
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "x-man.labels" . | nindent 8 }}
        app.kubernetes.io/name: docker-test-openldap
        app.kubernetes.io/version: {{ .Values.ldap.version | quote }}
        app.kubernetes.io/component: authentication
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "x-man.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: docker-test-openldap
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image:  "{{ .Values.ldap.image }}:{{ .Values.ldap.version }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: ldap
              containerPort: 10389
              protocol: TCP
            - name: ldaps
              containerPort: 10636
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ldapsearch
                - -H
                - ldap://localhost:10389
                - -x
                - -b
                - "ou=people,dc=planetexpress,dc=com"
                - cn
          readinessProbe:
            exec:
              command:
                - ldapsearch
                - -H
                - ldap://localhost:10389
                - -x
                - -b
                - "ou=people,dc=planetexpress,dc=com"
                - cn
          {{- with .Values.ldap.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
