{{- if .Values.mongodb.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "x-man.fullname" . }}-mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "x-man.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    {{- include "x-man.selectorLabels" . | nindent 4 }}
{{- end }}