apiVersion: v1
kind: Service
metadata:
  name: {{ include "x-man.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "x-man.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server
    {{- include "x-man.selectorLabels" . | nindent 4 }}
