apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-man.fullname" . }}-server
  labels:
    {{- include "x-man.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "x-man.name" . }}-server
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      {{- include "x-man.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "x-man.name" . }}-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "x-man.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "x-man.name" . }}-server
        app.kubernetes.io/component: server
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "x-man.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image:  "{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/server:{{ .Values.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: "80"
            - name: GIN_MODE
              value: release
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: ORIGIN
              value: {{ include "x-man.origin" . }}
            - name: LOGIN_TOKEN_LIFETIME_DAYS
              value: {{ .Values.app.loginTokenLifetimeDays | quote }}
            - name: DELETE_ARCHIVED_SUBMISSIONS_AFTER_DAYS
              value: {{ .Values.app.deleteArchivedSubmissionsAfterDays | quote }}
            - name: DELETE_ERRORS_AFTER_DAYS
              value: {{ .Values.app.deleteErrorsAfterDays | quote }}
            - name: INSTITUTION_NAME
              value: {{ .Values.app.institutionName | quote }}
            - name: INSTITUTION_ABBREVIATION
              value: {{ .Values.app.institutionAbbreviation | quote }}
            - name: APPRAISAL_LEVEL
              value: {{ .Values.app.appraisalLevel | quote }}
            - name: MAX_RECORD_DEPTH
              value: {{ .Values.app.maxRecordDepth | quote }}
            - name: POST_OFFICE_EMAIL
              value: {{ .Values.app.postOfficeEmail | quote }}
            - name: ARCHIVE_TARGET
              value: filesystem
            - name: REPORT_URL
              value: http://{{ include "x-man.fullname" . }}-report
            - name: MONGODB_URL
              {{- if .Values.mongodb.url }}
              value: {{ .Values.mongodb.url | quote }}
              {{- else }}
              value: mongodb://{{ include "x-man.fullname" . }}-mongodb:27017
              {{- end }}
            - name: MONGODB_USER
              value: {{ .Values.mongodb.user | quote }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password | quote }}
            - name: MONGODB_DB
              value: {{ .Values.mongodb.database | quote }}
            - name: LDAP_URL
              {{- if .Values.ldap.url }}
              value: {{ .Values.ldap.url | quote }}
              {{- else }}
              value: ldap://{{ include "x-man.fullname" . }}-ldap:10389
              {{- end }}
            - name: LDAP_TLS_INSECURE_SKIP_VERIFY
              {{- if .Values.ldap.url }}
              value: {{ .Values.ldap.tlsInsecureSkipVerify | quote }}
              {{- else }}
              value: "true"
              {{- end }}
            - name: LDAP_CONFIG
              value: {{ .Values.ldap.ldapConfig | quote }}
            - name: LDAP_BASE_DN
              value: {{ .Values.ldap.baseDn | quote }}
            - name: LDAP_USER
              value: {{ .Values.ldap.user | quote }}
            - name: LDAP_PASSWORD
              value: {{ .Values.ldap.password | quote }}
            - name: LDAP_ACCESS_GROUP
              value: {{ .Values.ldap.accessGroup | quote }}
            - name: LDAP_ADMIN_GROUP
              value: {{ .Values.ldap.adminGroup | quote }}
            - name: SMTP_SERVER
              value: {{ .Values.smtp.server | quote }}
            - name: SMTP_TLS_MODE
              value: {{ .Values.smtp.tlsMode | quote }}
            - name: SMTP_USER
              value: {{ .Values.smtp.user | quote }}
            - name: SMTP_PASSWORD
              value: {{ .Values.smtp.password | quote }}
            - name: SMTP_FROM_EMAIL
              value: {{ .Values.smtp.fromEmail | quote }}
            - name: BORG_URL
              value: {{ .Values.borg.url | quote }}
      {{- with .Values.server.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
