apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-man.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "x-man.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "x-man.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: server
        {{- include "x-man.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "x-man.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image:  "{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/server:{{ .Values.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: "80"
            - name: GIN_MODE
              value: release
            - name: TZ
              value: {{ .Values.timezone }}
            - name: ORIGIN
              value: {{ include "x-man.origin" . }}
            - name: MONGODB_URL
              {{- if .Values.mongodb.create }}
              value: mongodb://{{ include "x-man.fullname" . }}-mongodb:27017
              {{- else }}
              value: {{ .Values.mongodb.url }}
              {{- end }}
            - name: MONGODB_USER
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_DB
              value: {{ .Values.mongodb.database }}
      {{- with .Values.server.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
