{{- define "borg.serverConfig" -}}
tools:
  {{- range $key, $tool := .Values.tools }}
  {{- if $tool.enabled }}
  {{- range $tool.configurations }}
  - toolName: {{ .toolName | quote }}
    toolVersion: {{ .toolVersion | quote }}
    endpoint: http://{{ include "borg.fullname" $ }}-{{ $key }}{{ .path }}
    {{- with .features }}
    features:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .trigger }}
    trigger:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
