apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "borg.fullname" . }}
  labels:
    {{- include "borg.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    {{- toYaml .Values.shareVolume.resources | nindent 4 }}
  {{- with .Values.shareVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.shareVolume.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}