apiVersion: v1
kind: Service
metadata:
  name: {{ include "borg.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "borg.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server
    {{- include "borg.selectorLabels" . | nindent 4 }}
