{{- range $key, $tool := .Values.tools }}
{{- if $tool.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "borg.fullname" $ }}-{{ $key }}
  labels:
    app.kubernetes.io/component: tool-{{ $key }}
    {{- include "borg.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: tool-{{ $key }}
    {{- include "borg.selectorLabels" $ | nindent 4 }}
---
{{- end }}
{{- end }}