{{- range $key, $tool := .Values.tools }}
{{- if $tool.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg.fullname" $ }}-{{ $key }}
  labels:
    app.kubernetes.io/component: tool-{{ $key }}
    {{- include "borg.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: tool-{{ $key }}
      {{- include "borg.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: tool-{{ $key }}
        {{- include "borg.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg.serviceAccountName" $ }}
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $key }}
          {{- with $.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $.Values.imageRegistry }}/{{ $.Values.imageRootRepository }}/{{ $key }}:{{ $.Values.imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with $tool.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: share
              mountPath: /borg/file-store
          env:
            - name: PORT
              value: "80"
            - name: GIN_MODE
              value: release
      volumes:
        - name: share
          persistentVolumeClaim:
            claimName:  {{ include "borg.fullname" $ }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}